<?php

namespace ecommerce\BonsBundle\Repository;

/**
 * bonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bonRepository extends \Doctrine\ORM\EntityRepository
{
}
