<?php

namespace ecommerce\BonsBundle\Repository;

/**
 * detailBonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detailBonRepository extends \Doctrine\ORM\EntityRepository
{
}
