<?php

namespace ecommerce\produitBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 use Doctrine\ORM\EntityRepository;
class produitRepository extends EntityRepository
{
	 public function byCategorie($categ)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
				->distinct(true)
                ->where('u.categorie = :categ')
                ->orderBy('u.id')
                ->setParameter('categorie', $categ);
        return $qb->getQuery()->getResult();
    }
	 public function byCategorieHF($categ)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.categorieHF = :categ')
                ->orderBy('u.id')
                ->setParameter('categorieHF', $categ);
        return $qb->getQuery()->getResult();
    }
	    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.id IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
	
	
}
